---
-
  hosts: linux
  gather_facts: no
  tasks:
    - name: uname collect
      shell: uname -a
      register: uname

    - debug: var=uname.stdout_lines

    - name: time collect
      shell: chronyc activity || ntpstat; chronyc sources || ntpq -p; date
      register: timestatus

    - debug: var=timestatus.stdout_lines

    - name: disk
      shell: df -h; df -i; fdisk -l
      register: diskstatus

    - debug: var=diskstatus.stdout_lines

    - name: hashes
      shell: sha256sum /etc/shadow /etc/sudoers /etc/ssh/sshd_config
      register: hashes

    - debug: var=hashes.stdout_lines

    - name: process list
      shell: ps uaxwww
      register: psstatus

    - debug: var=psstatus.stdout_lines

    - name: open files
      shell: lsof
      register: lsofstatus

    - debug: var=lsofstatus.stdout_lines

    - name: ss -tanu
      shell: ss -tanu || netstat -tanu
      register: netstatus

    - debug: var=netstatus.stdout_lines


-
  hosts: centos
  gather_facts: no
  tasks:

    - name: sestatus
      shell: sestatus
      register: sestatus

    - debug: var=sestatus.stdout_lines

    - name: firewalld list
      shell: firewall-cmd --list-all
      register: fwstatus

    - debug: var=fwstatus.stdout_lines

    - name: yum hist
      shell: rpm -qa -last
      register: yum

    - debug: var=yum.stdout_lines

-
  hosts: debian
  gather_facts: no
  tasks:

    - name: ufw status
      shell: ufw status
      register: ufwstatus

    - debug: var=ufwstatus.stdout_lines

    - name: deb history
      shell: dpkg -l
      register: debhist

    - debug: var=debhist.stdout_lines

...
